plugins {
	id "net.fabricmc.fabric-loom" version "1.15-SNAPSHOT"
}

version = project.mod_version
group = project.maven_group

repositories {
	mavenCentral()
	maven { url "https://maven.terraformersmc.com" } //modmenu
	maven { url "https://maven.nucleoid.xyz" }
	maven { url "https://maven.shedaniel.me/" }

	maven {
		name = "Modrinth"
		url = "https://api.modrinth.com/maven"
		content {
			includeGroup "maven.modrinth"
		}
	}

}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"

	implementation "net.fabricmc:fabric-loader:${project.fabric_loader}"
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api}"

	implementation("me.shedaniel.cloth:cloth-config-fabric:${project.cloth_config}") {
		exclude(group: "net.fabricmc.fabric-api")
	}
	implementation("com.terraformersmc:modmenu:${project.modmenu_version}")
}

base {
	archivesName = project.archives_base_name
}

processResources {
    def expandProps = [
            "version": rootProject.mod_version,
            "minecraft_version_range": rootProject.minecraft_version_range,
    ]

    filesMatching(["fabric.mod.json"]) {
        expand expandProps
    }

    inputs.properties(expandProps)
}

tasks.withType(JavaCompile).configureEach {
	it.options.encoding = "UTF-8"
	it.options.release = 25
}

java {
	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
	withSourcesJar()
}

jar {
	inputs.property "archivesName", project.base.archivesName

	from("LICENSE") {
		rename { "${it}_${inputs.properties.archivesName}"}
	}
}
