plugins {
	id "fabric-loom" version "1.14-SNAPSHOT"
}

version = project.mod_version
group = project.maven_group

repositories {
	//maven { url "https://maven.shedaniel.me/" } //cloth-config
	//maven { url "https://maven.terraformersmc.com" } //modmenu
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings loom.officialMojangMappings()
	modImplementation "net.fabricmc:fabric-loader:${project.fabric_loader}"
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api}"

	modImplementation files("libs/cloth-config-fabric-21.11.151-fabric.jar")
	modImplementation files("libs/basic-math-0.6.1.jar")
	modImplementation files("libs/modmenu-17.0.0-alpha.1.jar")
}

base {
	archivesName = project.archives_base_name
}

processResources {
    def expandProps = [
            "version": rootProject.mod_version,
            "minecraft_version_range": rootProject.minecraft_version_range,
    ]

    filesMatching(["fabric.mod.json"]) {
        expand expandProps
    }

    inputs.properties(expandProps)
}

tasks.withType(JavaCompile).configureEach {
	it.options.encoding = "UTF-8"
	it.options.release = 21
}

java {
	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
	withSourcesJar()
}

jar {
	from("LICENSE") {
		rename { "${it}_${project.base.archivesName.get()}"}
	}
}
