# Done to increase the memory available to gradle.
org.gradle.jvmargs = -Xmx2G
org.gradle.parallel = true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Mod Properties
mod_version = 0.7.14+26.2
maven_group = ru.pinkgoosik
archives_base_name = visuality

minecraft_version_range = >=26.2 <26.3
modrinth_id = rI0hvYcd
curseforge_id = 521126

# Dependencies | Check these on https://fabricmc.net/develop
minecraft_version = 26.2
fabric_loader = 0.19.3
fabric_api = 0.152.1+26.2

cloth_config = 26.2.155
modmenu_version = 20.0.0-beta.2
