# Done to increase the memory available to gradle.
org.gradle.jvmargs = -Xmx2G
org.gradle.parallel = true

# Mod Properties
mod_version = 0.7.10+1.21.5
maven_group = ru.pinkgoosik
archives_base_name = visuality

minecraft_version_range = >=1.21.2 <1.22
modrinth_id = rI0hvYcd
curseforge_id = 521126

# Dependencies | Check these on https://fabricmc.net/develop
minecraft_version = 1.21.5-pre2
yarn_mappings = 1.21.5-pre2+build.6
fabric_loader = 0.16.10
fabric_api = 0.119.0+1.21.5

cloth_config = 16.0.141
modmenu_version = 13.0.0-beta.1
