# Done to increase the memory available to gradle.
org.gradle.jvmargs = -Xmx2G
org.gradle.parallel = true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Mod Properties
mod_version = 0.7.13+26.1
maven_group = ru.pinkgoosik
archives_base_name = visuality

minecraft_version_range = >=26.1 <26.2
modrinth_id = rI0hvYcd
curseforge_id = 521126

# Dependencies | Check these on https://fabricmc.net/develop
minecraft_version = 26.1
fabric_loader = 0.18.4
fabric_api = 0.144.0+26.1

cloth_config = 26.1.154
modmenu_version = 18.0.0-alpha.7
